name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: raffy-gke-terraform

      # Step 4: Authenticate Docker with Google Artifact Registry
      - name: Authenticate Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Step 5: Build and Push Docker Image
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=us-central1-docker.pkg.dev/raffy-gke-terraform/testrepository/nodeimage1:${{ github.sha }}
          docker build -t $IMAGE_TAG -f nodeapp/Dockerfile nodeapp
          docker push $IMAGE_TAG

      # Step 6: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          #install gke-gcloud-auth-plugin
          gcloud components install gke-gcloud-auth-plugin
          IMAGE_TAG=us-central1-docker.pkg.dev/raffy-gke-terraform/testrepository/nodeimage1:${{ github.sha }}
          sed -i "s|{{IMAGE_TAG}}|${IMAGE_TAG}|g" k8s/deploy.yml
          # Authenticate with the GKE cluster
          gcloud container clusters get-credentials cost-optimized-cluster-1 --zone us-central1-c --project raffy-gke-terraform

          # Apply Kubernetes manifests
          kubectl apply -f k8s/deploy.yml
          kubectl apply -f k8s/service.yml